<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	// データのクリア
    	DB::table('users')->truncate();

        DB::table('users')->insert([
        	[
			'id' => '1',
			'name' => 'きたしょー',
			'email' => 'kita.piece29@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元銀行員フリーランスエンジニアのきたしょーです。',
			'catch_phrase' => 'いつでもどこでも自由に生きていける。',
			'area' => '関東',
			'category' => 'プログラミング',
			'attribute' => 'フリーランス',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'プログラミング',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '2',
			'name' => 'みなしょー',
			'email' => 'kita.piece39@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元公務員社長エンジニアのみなしょーです。',
			'catch_phrase' => 'いつでもどこでも自由に生きていけるかも。',
			'area' => '九州',
			'category' => 'ブログ',
			'attribute' => '経営者',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ブログ',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '3',
			'name' => 'にししょー',
			'email' => 'kita.piece49@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元土木作業員エンジニアのみなしょーです。',
			'catch_phrase' => 'いつでもどこでも自由に生きていきたい。',
			'area' => '四国',
			'category' => 'プログラミング',
			'attribute' => '会社員',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ライティング',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '4',
			'name' => 'ひがしょー',
			'email' => 'kita.piece59@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのひがしょーです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '北海道',
			'category' => 'マーケティング',
			'attribute' => 'フリーランス',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '5',
			'name' => 'きたむ',
			'email' => 'kita.piece69@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのきたむです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '東北',
			'category' => 'YouTube',
			'attribute' => '経営者',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '6',
			'name' => 'きたむ',
			'email' => 'kita.piece79@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのきたぼです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '中部',
			'category' => 'イラスト',
			'attribute' => '会社員',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '7',
			'name' => 'しょーへい',
			'email' => 'kita.piece89@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのしょーへいです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '中国',
			'category' => '写真',
			'attribute' => 'フリーランス',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '8',
			'name' => 'きたろー',
			'email' => 'kita.piece99@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのきたろーです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '関東',
			'category' => 'YouTube',
			'attribute' => '会社員',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '9',
			'name' => 'きたお',
			'email' => 'kita.piece19@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのきたおです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '近畿',
			'category' => 'コーチング',
			'attribute' => 'フリーランス',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
			[
			'id' => '10',
			'name' => 'きたまる',
			'email' => 'kita.piece09@gmail.com',
			'email_verified_at' => new DateTime(),
			'password' => bcrypt('11111111'),
			'created_at' => new DateTime(),
			'updated_at' => new DateTime(),
			'profile_img_path' => 'test',
			'profile_img_upload' => new DateTime(),
			'profile_text' => '元エンジニアフリーランスのきたまるです。',
			'catch_phrase' => 'いつでもどこでも自由に生きる。',
			'area' => '中部',
			'category' => 'ダイエット',
			'attribute' => '経営者',
			'account_twitter' => '@KitamuraShohei',
			'account_facebook' => 'shohei.kitamura.31',
			'account_instagram' => 'kitamura_shohei',
			'url_twitter' => 'https://twitter.com/KitamuraShohei',
			'url_facebook' => 'https://www.facebook.com/shohei.kitamura.31/',
			'url_instagram' => 'https://www.instagram.com/kitamura_shohei/',
			'url_main' => 'https://kitashooo.com',
			'interest' => 'ボディメイク',
			'credit_card' => 0000000000000000,
			'bank_account' => 1234567,
			'is_identified' => 1,
			'is_active' => 1,
			'is_login' => 1,
			'is_requested' => 0,
			'last_login_date' => new DateTime(),
			'is_official' => 1,
			'is_nda_contracted' => 1,
			],
        ]);
    }
}
